
   
DROP PROCEDURE ContainsKey IF EXISTS;

DROP PROCEDURE Get IF EXISTS;

DROP PROCEDURE GetKV IF EXISTS;

DROP PROCEDURE Iterator  IF EXISTS;

DROP PROCEDURE GetParam IF EXISTS;

DROP PROCEDURE RemoveKeyValuePair IF EXISTS;

DROP PROCEDURE Remove IF EXISTS;

DROP PROCEDURE RemoveAll IF EXISTS;

DROP PROCEDURE Put IF EXISTS;

DROP PROCEDURE GetAndPut IF EXISTS;

DROP PROCEDURE GetAndRemove IF EXISTS;

DROP PROCEDURE GetAndReplace IF EXISTS;

DROP PROCEDURE PutIfAbsent IF EXISTS;

DROP PROCEDURE Replace IF EXISTS;

DROP PROCEDURE ReplaceKeyValuePair IF EXISTS;

DROP PROCEDURE Invoke IF EXISTS;

DROP table kv_parameters IF EXISTS;

DROP TABLE kv  IF EXISTS;

DROP STREAM kv_deltas IF EXISTS;